version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neo-reddit-db
    ports:
      - "5432:5432"
    volumes:
      - neo-reddit-db:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      target: "base"
    command: "yarn dev"
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_NAME: neo-reddit-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis
      SESSION_SECRET: my_secret
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app

volumes:
  neo-reddit-db:
